getwd()
mvt = read.csv("mvtWeek1.csv")
str(mvt)
summary(mvt)
      
which.max(mvt$ID)
mvt$ID[18134]
mvt$Beat[which.min(mvt$Beat)]
which.min(mvt$Beat)
mvt$Beat[4756]
table(mvt$Arrest)
table(mvt$LocationDescription)

match("ALLEY",mvt$LocationDescription
mvt$Date[1]
DateConvert = as.Date(strptime(mvt$Date,"%m/%d/%y %H:%M"))
summary(DateConvert) 
mvt$month = months(DateConvert)
mvt$Weekday = weekdays(DateConvert)
mvt$Date = DateConvert
table(mvt$month)
which.min()
which.min(table(mvt$month)) 
table(mvt$Weekday) 
which.max(table(mvt$Weekday))
table(mvt$Arrest,mvt$month)
hist(mvt$Date,breaks = 100)
boxplot(mvt$Date,mvt$Arrest)
table(mvt$Arrest)
tapply(mvt$Date,mvt$Arrest,summary,na.rm=TRUE)
str(mvt)
table(mvt$Arrest,mvt$Year)
table(mvt$LocationDescription)
sort(table(mvt$LocationDescription))
Top5 = subset(mvt,mvt$Arrest == TRUE)
str(Top5)
match("STREET",mvt$LocationDescription)
Top5 = subset(mvt,match("STREET", mvt$LocationDescription)==TRUE)
str(Top5)
Top5 = subset(mvt,LocationDescription=="STREET" | LocationDescription=="GAS STATION" | LocationDescription=="DRIVEWAY - RESIDENTIAL" | LocationDescription=="")
Top5 = subset(mvt,LocationDescription=="STREET" | LocationDescription=="GAS STATION" | LocationDescription=="DRIVEWAY - RESIDENTIAL" | LocationDescription=="ALLEY" | LocationDescription == "PARKING LOT/GARAGE(NON.RESID.)")
str(Top5)
TopLocations = c("STREET", "PARKING LOT/GARAGE(NON.RESID.)", "ALLEY", "GAS STATION", "DRIVEWAY - RESIDENTIAL")
TopLocations = c("STREET", "PARKING LOT/GARAGE(NON.RESID.)", "ALLEY", "GAS STATION", "DRIVEWAY - RESIDENTIAL")
TopLocations = c("STREET", "PARKING LOT/GARAGE(NON.RESID.)", "ALLEY", "GAS STATION", "DRIVEWAY - RESIDENTIAL")
TopLocations = c("STREET", "PARKING LOT/GARAGE(NON.RESID.)", "ALLEY", "GAS STATION", "DRIVEWAY - RESIDENTIAL")
Top5 = subset(mvt, LocationDescription %in% TopLocations)
str(Top5)
Top5$LocationDescription = factor(Top5$LocationDescription)
table(Top5$LocationDescription)
str(Top5$LocationDescription)
table(Top5$LocationDescription,Top5$Arrest)
table(Top5$LocationDescription,Top5$Weekday)