getwd()
poll = read.csv("AnonymityPoll.csv")
str(poll)
table(poll$Smartphone)
summary(poll)
table(poll$Region,poll$State)
table(poll$Internet,poll$Smartphone)
limited = subset(poll,poll$Internet== TRUE | poll$Smartphone ==TRUE)
str(limited)
summary(limited)    
mean(limited$Info.On.Internet)
table(limited$Info.On.Internet)
tapply(limited$Info.On.Internet,limited$Worry.About.Info == TRUE,mean)
table(limited$Worry.About.Info)
table(limited$Anonymity.Possible)
table(limited$Tried.Masking.Identity)
table(limited$Privacy.Laws.Effective)
hist(limited$Age)
plot(limited$Age,limited$Info.On.internet)
plot(limited$Age,limited$Info.On.Internet)
table(limited$Age,limited$Info.On.Internet)
max(table(limited$Age,limited$Info.On.Internet))
jitter(c(1,2,3))
plot(jitter(limited$Age),jitter(limited$Info.On.Internet))
tapply(limited$Info.On.Internet,limited$Smartphone,summary)
tapply(limited$Tried.Masking.Identity,limited$Smartphone,summary)
table(limited$Smartphone,limited$Tried.Masking.Identity)
tapply(limited$Tried.Masking.Identity,limited$Smartphone,mean)
tapply(limited$Tried.Masking.Identity,limited$Smartphone,mean,na.rm=TRUE)