str(CPS)
CPS = merge(CPS,MetroAreaMap,by.x="MetroAreaCode",by.y="Code",all.x =TRUE)
str(CPS)
table(is.na(CPS$MetroArea))
sort(table(CPS$MetroArea))
table(CPS$MetroArea)
sort(tapply(is.na(CPS$MetroArea),CPS$Hispanic,mean))
sort(tapply(CPS$Hispanic,CPS$MetroArea,mean))
sort(tapply(CPS$Race=="Asian",CPS$MetroArea,mean))
sort(tapply(CPS$Education == "No high school diploma",CPS$MetroArea,mean,na.rm=TRUE))
sort(tapply(CPS$Education == "No high school diploma",CPS$MetroArea,mean,na.rm=TRUE))
ls()
str(CPS)
str(CountryMap)
CPS=merge(CPS,CountryMap,by.x="CountryOfBirthCode",by.y="Code",all.x=TRUE)
str(CPS)
table(is.na(CPS$Country))
table(CPS$Country)
tapply(is.na(CPS$MetroArea),CPS$Region =="New York-Northern New Jersey-Long Island, NY-NJ-PA",mean,na.rm=TRUE)
table(CPS$MetroArea=="New York-Northern New Jersey-Long Island, NY-NJ-PA",CPS$Country != "United States")
getwd()
CPS = read.csv("CPSData.csv")
MetroAreaMap = read.csv("MetroAreaCodes.csv")
CountryMap =read.csv("CountryCodes.csv")
str(CPS)
str(MetroAreaMap)
str(CountryMap)
CPS = merge(CPS,MetroAreaMap,by.x="MetroAreaCode",by.y="Code",all.x =TRUE)
str(CPS)
CPS = merge(CPS,CountryMap,by.x = "CountryOfBirthCode",by.y="Code",all.x=TRUE)
str(CPS)
str(CPS)
table(is.na(CPS$Country))
sort(table(CPS$Country))
str(CPS)
tapply(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA",CPS$Country,mean)
table(CPS$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA",CPS$Country != "United States")
tapply(CPS$Country == "India",CPS$MetroArea,max,na.rm =TRUE)
sort(tapply(CPS$Country == "India",CPS$MetroArea,max,na.rm =TRUE))
sort(tapply(CPS$Country == "India",CPS$MetroArea,sum,na.rm =TRUE))
sort(tapply(CPS$Country == "Brazil",CPS$MetroArea,sum,na.rm =TRUE))
sort(tapply(CPS$Country == "Somalia",CPS$MetroArea,sum,na.rm =TRUE))