setwd("D:/Study/Data Science/The Analytics Edge-edX/Assignment 2")
getwd()
Elantra = read.csv("elantra.csv")
str(Elantra)
ElantraTrain = subset(Elantra, Year <= 2012)
str(ElantraTrain)
ElantraTest = subset(Elantra, Year > 2012)
str(ElantraTest)
ElanModel = lm(ElantraSales ~  Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElanModel)
ElanModel_M = lm(ElantraSales ~ Month + Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElanModel_M)
ElantraTrain$Month = as.factor(ElantraTrain$Month)
str(ElantraTrain)
ElanModel_M = lm(ElantraSales ~ Month + Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElanModel_M)
plot(ElantraTrain$Month,ElantraTrain$ElantraSales)
plot(ElantraTrain$Month,ElantraTrain$ElantraSales)
ElantraTrain$Month = as.numeric(ElantraTrain$Month)
str(ElantraTrain)
plot(ElantraTrain$Month,ElantraTrain$ElantraSales)
ElantraTrain$Month = as.numeric(ElantraTrain$Month)
str(ElantraTrain)
ElantraTrain$MonthF = as.factor(ElantraTrain$Month)
str(ElantraTrain)
ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElanModel_M)
str(ElantraTrain)

cor(ElantraTrain$CPI_energy, ElantraTrain$Month)
cor(ElantraTrain$CPI_energy, ElantraTrain$Unemployment)
cor(ElantraTrain$CPI_energy, ElantraTrain$Queries)
cor(ElantraTrain$CPI_energy, ElantraTrain$CPI_all)
cor(ElantraTrain[c("Unemployment","CPI_all","CPI_energy","Month","Queries")])

ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_all + CPI_energy + Queries, data = ElantraTrain)
summary(ElanModel_M)
ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_all + CPI_energy, data = ElantraTrain)
summary(ElanModel_M)
ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_all, data = ElantraTrain)
summary(ElanModel_M)
ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_energy, data = ElantraTrain)
summary(ElanModel_M)
ElanModel_M = lm(ElantraSales ~ MonthF + Unemployment + CPI_all + CPI_energy, data = ElantraTrain)
summary(ElanModel_M)
ls()
str(ElantraTrain)
ElantraTest$MonthF = as.factor(ElantraTest$Month)
str(ElantraTest)
PredElantra = predict(ElanModel_M,newdata = ElantraTest)
Error = PredElantra - ElantraTest$ElantraSales
SE = Error^2
SSE = sum(SE)
SSE
mean(ElantraTrain$ElantraSales)
SST = sum((mean(ElantraTrain$ElantraSales) - ElantraTest$ElantraSales)^2)
SST
AE1 = mean(ElantraTrain$ElantraSales) - ElantraTest$ElantraSales 
max(abs(PredElantra - ElantraTest$ElantraSales))
AE = abs(PredElantra - ElantraTest$ElantraSales)
which.max(AE)
ElantraTest$Month[5]
ElantraTest$Year[5]