setwd("D:Study/Data Science/The Analytics Edge-edX/Hands On")
getwd()
Framingham = read.csv("Framingham.csv")
str(Framingham)
library(caTools)
set.seed(1000)
split = sample.split(Framingham$TenYearCHD, SplitRatio = 0.65)
train_F = subset(Framingham, split == "TRUE")
test_F = subset(Framingham, split == "FALSE")
nrow(train_F)
nrow(test_F)
table(split)
FraminghamLog = glm(TenYearCHD ~ ., data = train_F , family = binomial)
summary(FraminghamLog)
predTest = predict(FraminghamLog, type = "response", newdata = test_F)
table(test_F$TenYearCHD, predTest > 0.5)

library(ROCR)
ROCRpred = prediction(predTest, test_F$TenYearCHD)
auc = as.numeric(performance(ROCRpred,"auc")@y.values)
auc